# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-30 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luck', '0002_auto_20181230_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='luck.User'),
        ),
    ]
