# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-12-31 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luck', '0004_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
