# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luck', '0007_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='luck.User'),
        ),
    ]
