# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-02 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luck', '0009_auto_20190102_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='luckybucks',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
